<?php

// GET homepage, show all posts:
Route::get('/', 'PostsController@index')->name('home');
// GET /posts/create, show form for creating post:
Route::get('/posts/create', 'PostsController@create');
// POST /posts, save new post:
Route::post('/posts', 'PostsController@store');
// GET /posts/{post}, show one post:
Route::get('/posts/{post}', 'PostsController@show');

// POST /posts/{post}/comments, save comment to post:
Route::post('/posts/{post}/comments', 'CommentsController@store');

Route::get('/posts/{post}/delete', 'PostsController@destroyConfirm');
Route::post('/posts/{post}/delete', 'PostsController@destroy');

Route::get('/posts/{post}/edit', 'PostsController@edit');
Route::post('/posts/{post}/edit', 'PostsController@update');

// Route::get('/comments/{comment}/edit', 'CommentsController@edit');
// ^
// Was really hard to get working, so it's commented out.

Auth::routes();
// ^ 
// This was generated by:
// php artisan make:auth
// Sets up routes for 
//      /login, /register, and /home
// Which all do what you think.

Route::get('/home', 'HomeController@index');
// Also generated by the make:auth command.